name: Postman-Build
on:
  push:
    branches:
      - main

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
    # Check out repository
    - uses: actions/checkout@v2
      
    # Install Node
    - name: Install Node
      uses: actions/setup-node@v1
      with: 
        node-version: '16.x'
    
    # Install newman
    - name: Install newman
      run: |
       npm install -g newman
       
    # Install html extra reporter
    - name: Install html extra reporter
      run: |
       npm install -g newman-reporter-htmlextra

    # Make directory for results
    - name: Make directory for results
      run: mkdir -p testResults

    # Run newman
    - name: Run newman
      run: |
       newman run ./API Test Automation/JSON_Placeholder_API.postman_collection.json -e ./API Test Automation/DEV.postman_environment.json -r htmlextra --reporter-htmlextra-export testResults/htmlreport.html --reporter-htmlextra-darkTheme  > testResults/runreport1.html

    # Upload the contents of Test Results directory to workspace
    - name: Output the run Details
      uses: actions/upload-artifact@v2
      with: 
       name: RunReports
       path: testResults
